In [1]:
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_sas('data/rata_s_srs_an.sas7bdat', encoding='iso8859-1')

In [3]:
df.head()

,COD_PRDA_RATE,IMP_APL_FINZ,IMP_CPT_FINZ,NUM_RATE,IMP_RATE_MENS,IMP_MAX_UNPAIDINS,Contract_ID
0,M,950000.0,950000.0,24.0,41310.0,NaN,S_000001
1,M,50000.0,50000.0,12.0,4611.0,NaN,S_000003
2,M,100000.0,100000.0,42.0,2960.0,0.0,S_000004
3,M,3600434.0,2324160.0,49.0,48420.0,60143.0,S_000005
4,M,211776.0,211776.0,85.0,2930.0,1256.0,S_000006

In [4]:
df['COD_PRDA_RATE'].unique()

array(['M', 'V', 'A', 'T', 'N', 'S'], dtype=object)

**Goal:** Summary statistics/operations per group in `COD_PRDA_RATE`.

In [5]:
df_avg = df.groupby('COD_PRDA_RATE')['IMP_CPT_FINZ', 'IMP_APL_FINZ'].mean()

**IMPORTANT:** To be sure that we really do create a copy (and not a reference) we can add .copy()

`small_df = df[['IMP_CPT_FINZ', 'IMP_APL_FINZ']].copy()`

In [6]:
df_avg

               IMP_CPT_FINZ  IMP_APL_FINZ
COD_PRDA_RATE
A              4.948496e+05           NaN
M              2.011674e+05  2.355360e+05
N              6.465252e+06  1.056474e+07
S              1.223761e+06  1.408094e+06
T              3.653297e+06  3.536394e+06
V              2.126372e+05  2.593555e+05

In [7]:
import numpy as np

In [8]:
def my_func(array):
    return np.sum(array)

In [9]:
df.groupby(['COD_PRDA_RATE', 'NUM_RATE'])['IMP_CPT_FINZ', 'IMP_APL_FINZ'].agg({
                                                                'IMP_CPT_FINZ':['mean', 'std'],
                                                                'IMP_APL_FINZ':my_func
})

                        IMP_CPT_FINZ               IMP_APL_FINZ
                                mean           std      my_func
COD_PRDA_RATE NUM_RATE
A             5.0       1.059000e+06           NaN          0.0
              10.0      1.000000e+05           NaN          0.0
              16.0      1.644646e+06           NaN          0.0
              48.0      3.000000e+04           NaN          0.0
              51.0      3.000000e+05           NaN          0.0
              67.0      1.000000e+05           NaN          0.0
              77.0      1.200000e+05           NaN          0.0
              78.0      1.000000e+06           NaN          0.0
              88.0      1.000000e+05           NaN          0.0
M             1.0       5.020890e+04  4.410830e+05  191320453.0
              2.0       1.851139e+05  7.496102e+05   36536548.0
              3.0       2.474835e+05  7.463264e+05   27810635.0
              4.0       5.382752e+04  2.965818e+05   31542386.0
              5.0       6.041594e+04  3.295544e+05   72303425.0
              6.0       3.935282e+04  2.892209e+05   56226349.0
              7.0       1.258711e+05  4.928911e+05   68489967.0
              8.0       8.081620e+04  2.445332e+05   53728235.0
              9.0       3.608929e+04  1.841544e+05   82810407.0
              10.0      1.600735e+04  1.082244e+05  120005518.0
              11.0      9.506183e+04  3.896496e+05  145501263.0
              12.0      6.054076e+04  2.084498e+05  268860714.0
              13.0      1.714512e+05  4.199262e+05  145478086.0
              14.0      1.602700e+05  4.130287e+05   79157381.0
              15.0      7.481962e+04  3.355842e+05   86737883.0
              16.0      1.574904e+05  5.710676e+05   69658192.0
              17.0      1.936731e+05  5.260546e+05   85389343.0
              18.0      1.064452e+05  3.113488e+05   92593039.0
              19.0      1.791161e+05  4.521186e+05   90084926.0
              20.0      3.844762e+04  1.972116e+05  123353750.0
              21.0      2.171196e+05  5.113184e+05   98107190.0
...                              ...           ...          ...
V             343.0     1.800000e+06  1.571623e+06    5200000.0
              344.0     5.043397e+05  2.104798e+05    1648000.0
              345.0     2.280000e+06           NaN          0.0
              346.0     1.208750e+06  6.358246e+05    4256000.0
              347.0     3.406667e+06  1.958605e+06    6220000.0
              348.0     1.123800e+06  7.057054e+05    3922191.0
              349.0     1.829718e+06  8.975905e+05   18075625.0
              351.0     1.352992e+06  8.759700e+05   15034200.0
              352.0     1.350000e+06           NaN    1400000.0
              353.0     1.458000e+06  9.489573e+05    7370000.0
              354.0     2.153566e+06  1.122292e+06   14799000.0
              355.0     1.699696e+06  6.733565e+05    4840784.0
              356.0     2.326490e+06  2.451396e+06   20311917.0
              357.0     1.775046e+06  1.174103e+06   14560368.0
              358.0     2.329650e+06  1.962352e+06   29205260.0
              359.0     1.949371e+06  2.301473e+06   33880000.0
              360.0     1.724083e+06  1.351230e+06   87658138.0
              361.0     1.425389e+06  9.443555e+05   17945000.0
              362.0     1.466333e+06  1.078796e+06    4399000.0
              365.0     1.000000e+06           NaN          0.0
              366.0     1.630000e+06           NaN          0.0
              369.0     2.719000e+06           NaN          0.0
              372.0     1.047500e+06  5.197235e+05    2095000.0
              384.0     1.450000e+06           NaN    1450000.0
              396.0     6.650000e+06           NaN    6650000.0
              420.0     7.775313e+05  7.657682e+05    2322593.0
              432.0     7.500000e+05           NaN     750000.0
              480.0     1.162000e+06           NaN    1162000.0
              504.0     1.000000e+06           NaN    1000000.0
              516.0     3.005077e+06  0.000000e+00    3150000.0

[744 rows x 3 columns]

In [10]:
df.columns

Index(['COD_PRDA_RATE', 'IMP_APL_FINZ', 'IMP_CPT_FINZ', 'NUM_RATE',
       'IMP_RATE_MENS', 'IMP_MAX_UNPAIDINS', 'Contract_ID'],
      dtype='object')

### Percentage of total
- **Goal**: Calculate percentage of total of `num_rate` vs `cod_prda_rate`.

In [21]:
cod_num = df.pivot_table(columns='COD_PRDA_RATE', 
               index='NUM_RATE', 
               values='IMP_CPT_FINZ', 
               aggfunc='count')

In [22]:
num = df.groupby('NUM_RATE')['IMP_CPT_FINZ'].count()

In [20]:
100*cod_num.div(num, level='NUM_RATE', axis=0, )

COD_PRDA_RATE         A           M         N         S         T           V
NUM_RATE
1.0                 NaN   59.891540  0.010846       NaN       NaN   40.097614
2.0                 NaN   64.524422       NaN       NaN       NaN   35.475578
3.0                 NaN   77.209302  0.465116       NaN       NaN   22.325581
4.0                 NaN   83.041401       NaN       NaN       NaN   16.958599
5.0            0.056625   90.147225  0.283126       NaN  0.056625    9.456399
6.0                 NaN   91.819292  0.040700       NaN       NaN    8.140008
7.0                 NaN   78.468368       NaN  0.110988       NaN   21.420644
8.0                 NaN   79.346867       NaN  0.176523       NaN   20.476611
9.0                 NaN   94.163424       NaN       NaN       NaN    5.836576
10.0           0.005700   98.495298  0.011399  0.011399       NaN    1.476204
11.0                NaN   88.334090       NaN       NaN  0.045393   11.620517
12.0                NaN   95.225619       NaN       NaN  0.145560    4.628821
13.0                NaN   81.719597       NaN       NaN  1.239349   17.041053
14.0                NaN   76.600698       NaN       NaN       NaN   23.399302
15.0                NaN   88.377581       NaN       NaN       NaN   11.622419
16.0           0.120192   73.317308       NaN  0.120192  0.360577   26.081731
17.0                NaN   74.837027       NaN       NaN  0.130378   25.032595
18.0                NaN   86.581470       NaN       NaN       NaN   13.418530
19.0                NaN   77.443609       NaN       NaN       NaN   22.556391
20.0                NaN   97.167398       NaN       NaN  0.073099    2.759503
21.0                NaN   73.587571       NaN       NaN  0.706215   25.706215
22.0                NaN   91.605218       NaN       NaN       NaN    8.394782
23.0                NaN   81.468111       NaN       NaN  0.240674   18.291215
24.0                NaN   98.448548       NaN       NaN  0.013730    1.537722
25.0                NaN   89.711064       NaN       NaN       NaN   10.288936
26.0                NaN   83.564815       NaN       NaN       NaN   16.435185
27.0                NaN   80.687398       NaN       NaN       NaN   19.312602
28.0                NaN   81.895332       NaN       NaN  0.141443   17.963225
29.0                NaN   80.797101       NaN       NaN       NaN   19.202899
30.0                NaN   96.537251       NaN       NaN       NaN    3.462749
...                 ...         ...       ...       ...       ...         ...
451.0               NaN  100.000000       NaN       NaN       NaN         NaN
452.0               NaN  100.000000       NaN       NaN       NaN         NaN
456.0               NaN  100.000000       NaN       NaN       NaN         NaN
457.0               NaN  100.000000       NaN       NaN       NaN         NaN
462.0               NaN  100.000000       NaN       NaN       NaN         NaN
463.0               NaN  100.000000       NaN       NaN       NaN         NaN
465.0               NaN  100.000000       NaN       NaN       NaN         NaN
466.0               NaN  100.000000       NaN       NaN       NaN         NaN
467.0               NaN  100.000000       NaN       NaN       NaN         NaN
468.0               NaN  100.000000       NaN       NaN       NaN         NaN
469.0               NaN  100.000000       NaN       NaN       NaN         NaN
470.0               NaN  100.000000       NaN       NaN       NaN         NaN
472.0               NaN  100.000000       NaN       NaN       NaN         NaN
474.0               NaN  100.000000       NaN       NaN       NaN         NaN
479.0               NaN  100.000000       NaN       NaN       NaN         NaN
480.0               NaN   75.000000       NaN       NaN       NaN   25.000000
481.0               NaN  100.000000       NaN       NaN       NaN         NaN
482.0               NaN  100.000000       NaN       NaN       NaN         NaN
483.0               NaN  100.000000       NaN       NaN       NaN         NaN
484.0               NaN  100.000000       NaN       NaN       NaN         NaN
487.0               NaN  100.000000       NaN       NaN       NaN         NaN
490.0               NaN  100.000000       NaN       NaN       NaN         NaN
492.0               NaN  100.000000       NaN       NaN       NaN         NaN
503.0               NaN  100.000000       NaN       NaN       NaN         NaN
504.0               NaN   66.666667       NaN       NaN       NaN   33.333333
505.0               NaN  100.000000       NaN       NaN       NaN         NaN
516.0               NaN         NaN       NaN       NaN       NaN  100.000000
528.0               NaN  100.000000       NaN       NaN       NaN         NaN
581.0               NaN  100.000000       NaN       NaN       NaN         NaN
999.0               NaN  100.000000       NaN       NaN       NaN         NaN

[446 rows x 6 columns]

In [24]:
100*pd.crosstab(index=df['NUM_RATE']
            , columns=df['COD_PRDA_RATE']
            , values=df['IMP_CPT_FINZ']
            , normalize='index'
            , dropna=False, aggfunc='count')

COD_PRDA_RATE         A           M         N         S         T           V
NUM_RATE
1.0            0.000000   59.891540  0.010846  0.000000  0.000000   40.097614
2.0            0.000000   64.524422  0.000000  0.000000  0.000000   35.475578
3.0            0.000000   77.209302  0.465116  0.000000  0.000000   22.325581
4.0            0.000000   83.041401  0.000000  0.000000  0.000000   16.958599
5.0            0.056625   90.147225  0.283126  0.000000  0.056625    9.456399
6.0            0.000000   91.819292  0.040700  0.000000  0.000000    8.140008
7.0            0.000000   78.468368  0.000000  0.110988  0.000000   21.420644
8.0            0.000000   79.346867  0.000000  0.176523  0.000000   20.476611
9.0            0.000000   94.163424  0.000000  0.000000  0.000000    5.836576
10.0           0.005700   98.495298  0.011399  0.011399  0.000000    1.476204
11.0           0.000000   88.334090  0.000000  0.000000  0.045393   11.620517
12.0           0.000000   95.225619  0.000000  0.000000  0.145560    4.628821
13.0           0.000000   81.719597  0.000000  0.000000  1.239349   17.041053
14.0           0.000000   76.600698  0.000000  0.000000  0.000000   23.399302
15.0           0.000000   88.377581  0.000000  0.000000  0.000000   11.622419
16.0           0.120192   73.317308  0.000000  0.120192  0.360577   26.081731
17.0           0.000000   74.837027  0.000000  0.000000  0.130378   25.032595
18.0           0.000000   86.581470  0.000000  0.000000  0.000000   13.418530
19.0           0.000000   77.443609  0.000000  0.000000  0.000000   22.556391
20.0           0.000000   97.167398  0.000000  0.000000  0.073099    2.759503
21.0           0.000000   73.587571  0.000000  0.000000  0.706215   25.706215
22.0           0.000000   91.605218  0.000000  0.000000  0.000000    8.394782
23.0           0.000000   81.468111  0.000000  0.000000  0.240674   18.291215
24.0           0.000000   98.448548  0.000000  0.000000  0.013730    1.537722
25.0           0.000000   89.711064  0.000000  0.000000  0.000000   10.288936
26.0           0.000000   83.564815  0.000000  0.000000  0.000000   16.435185
27.0           0.000000   80.687398  0.000000  0.000000  0.000000   19.312602
28.0           0.000000   81.895332  0.000000  0.000000  0.141443   17.963225
29.0           0.000000   80.797101  0.000000  0.000000  0.000000   19.202899
30.0           0.000000   96.537251  0.000000  0.000000  0.000000    3.462749
...                 ...         ...       ...       ...       ...         ...
451.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
452.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
456.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
457.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
462.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
463.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
465.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
466.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
467.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
468.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
469.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
470.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
472.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
474.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
479.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
480.0          0.000000   75.000000  0.000000  0.000000  0.000000   25.000000
481.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
482.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
483.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
484.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
487.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
490.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
492.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
503.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
504.0          0.000000   66.666667  0.000000  0.000000  0.000000   33.333333
505.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
516.0          0.000000    0.000000  0.000000  0.000000  0.000000  100.000000
528.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
581.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000
999.0          0.000000  100.000000  0.000000  0.000000  0.000000    0.000000

[446 rows x 6 columns]